server:
  port: 8080
  mode: dev

database:
  host: localhost
  port: 5432
  user: ductan
  password: 123456
  dbname: ecommerce
  maxOpenConnections: 10
  maxIdleConnections: 5
  maxLifetimeConnection: 3600

logger:
  level: debug
  format: json
  file_log_name: ./storages/logs/app.log

redis:
  host: localhost
  port: 6379
  password: 
  database: 0

jwt:
  tokenSecret: "secret"
  tokenExpirationTime: 24h
  tokenHoursToExpire: 24

smtp:
  host: smtp.gmail.com
  port: 587
  username: ndt11102003@gmail.com
  password: mnwmitfivjymkgzh

