name: GoCI/CD Docker Deployment

on:
  push:
    branches:
      - main  # Hoặc branch bạn muốn deploy khi có thay đổi

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t myapp:${{ github.sha }} .

      - name: Run Docker container
        run: |
          docker run -d -p 8080:8080 myapp:${{ github.sha }}
          sleep 10 
          curl http://localhost:8080/ping 
        
      - name: Check Docker container logs
        run: |
          docker ps 
          docker logs $(docker ps -q) 
